# Generated by Django 6.0.2 on 2026-05-11 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_attack', models.CharField(max_length=120)),
                ('classifier_confidence', models.FloatField(default=0.0)),
                ('network_anomaly_score', models.FloatField(default=0.0)),
                ('process_anomaly_score', models.FloatField(default=0.0)),
                ('window_start_time', models.DateTimeField()),
                ('window_end_time', models.DateTimeField()),
                ('technique_id', models.CharField(blank=True, default='', max_length=30)),
                ('llm_response', models.TextField(blank=True, default='')),
                ('recommended_actions', models.JSONField(blank=True, default=dict)),
                ('full_report', models.TextField(blank=True, default='')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
