# Generated by Django 6.0.2 on 2026-02-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('security_specialist', 'Security Specialist'), ('ai_engineer', 'AI Engineer'), ('external_user', 'External User')], max_length=30),
        ),
    ]
